# Generated by Django 4.2.6 on 2023-11-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='image',
            field=models.ImageField(upload_to='superheroes/images/'),
        ),
    ]
