# Generated by Django 4.2.4 on 2023-10-24 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('realName', models.CharField(max_length=50)),
                ('strength1', models.CharField(max_length=200)),
                ('strength2', models.CharField(max_length=200)),
                ('strength3', models.CharField(max_length=200)),
                ('weakness1', models.CharField(max_length=200)),
                ('weakness2', models.CharField(max_length=200)),
                ('weakness3', models.CharField(max_length=200)),
                ('imagePath', models.CharField(max_length=200)),
                ('reporter', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='SuperProfiles.reporter')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('tagline', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('imagePath', models.CharField(max_length=200)),
                ('reporter', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='SuperProfiles.reporter')),
            ],
        ),
    ]
