# Generated by Django 4.2.6 on 2023-11-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperProfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tagline',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='realName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='realName',
            field=models.CharField(max_length=100),
        ),
    ]
