# Generated by Django 4.2.5 on 2023-10-31 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='identity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='superhero',
            name='strength',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='superhero',
            name='weakness',
            field=models.CharField(default='', max_length=100),
        ),
    ]
